-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 01:19:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Classroon_Equipment_Booking_System
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Classroon_Equipment_Booking_System` ;

-- -----------------------------------------------------
-- Schema Classroon_Equipment_Booking_System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Classroon_Equipment_Booking_System` DEFAULT CHARACTER SET utf8 ;
USE `Classroon_Equipment_Booking_System` ;

-- -----------------------------------------------------
-- Table `Classroon_Equipment_Booking_System`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroon_Equipment_Booking_System`.`Member` ;

CREATE TABLE IF NOT EXISTS `Classroon_Equipment_Booking_System`.`Member` (
  `idMember` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `identity` VARCHAR(45) NULL,
  `password` VARCHAR(128) NULL,
  `salt` BINARY(16) NULL,
  PRIMARY KEY (`idMember`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classroon_Equipment_Booking_System`.`Borrow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroon_Equipment_Booking_System`.`Borrow` ;

CREATE TABLE IF NOT EXISTS `Classroon_Equipment_Booking_System`.`Borrow` (
  `idBorrow` INT NOT NULL,
  `timestamp` TIMESTAMP(6) NULL,
  `name` VARCHAR(45) NULL,
  `identity` VARCHAR(45) NULL,
  `departmentGrade` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `identitycard` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idBorrow`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classroon_Equipment_Booking_System`.`Classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroon_Equipment_Booking_System`.`Classroom` ;

CREATE TABLE IF NOT EXISTS `Classroon_Equipment_Booking_System`.`Classroom` (
  `idClassroom` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `image` BLOB NULL,
  PRIMARY KEY (`idClassroom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classroon_Equipment_Booking_System`.`Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroon_Equipment_Booking_System`.`Booking` ;

CREATE TABLE IF NOT EXISTS `Classroon_Equipment_Booking_System`.`Booking` (
  `idBooking` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `identity` VARCHAR(45) NULL,
  `idStudent` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `bookingReason` VARCHAR(45) NULL,
  `idClassroom` INT NULL,
  `bookingDate` DATE NULL,
  `startTime` VARCHAR(45) NULL,
  `endTime` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `id_borrow` INT NULL,
  PRIMARY KEY (`idBooking`),
  INDEX `id_borrow_idx` (`id_borrow` ASC),
  INDEX `id_Classroom_idx` (`idClassroom` ASC),
  CONSTRAINT `id_booking_borrow`
    FOREIGN KEY (`id_borrow`)
    REFERENCES `Classroon_Equipment_Booking_System`.`Borrow` (`idBorrow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_booking_classroom`
    FOREIGN KEY (`idClassroom`)
    REFERENCES `Classroon_Equipment_Booking_System`.`Classroom` (`idClassroom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classroon_Equipment_Booking_System`.`Borrow_Classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroon_Equipment_Booking_System`.`Borrow_Classroom` ;

CREATE TABLE IF NOT EXISTS `Classroon_Equipment_Booking_System`.`Borrow_Classroom` (
  `idBorrow_Classroom` INT NOT NULL,
  `idBorrow` INT NULL,
  `idClassroom` INT NULL,
  `timestamp` TIMESTAMP(6) NULL,
  `teacher` VARCHAR(45) NULL,
  `purpose` VARCHAR(45) NULL,
  `note` VARCHAR(45) NULL,
  PRIMARY KEY (`idBorrow_Classroom`),
  INDEX `idBorrow_idx` (`idBorrow` ASC),
  INDEX `idClassroom_idx` (`idClassroom` ASC),
  CONSTRAINT `id_Borrow`
    FOREIGN KEY (`idBorrow`)
    REFERENCES `Classroon_Equipment_Booking_System`.`Borrow` (`idBorrow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Classroom`
    FOREIGN KEY (`idClassroom`)
    REFERENCES `Classroon_Equipment_Booking_System`.`Classroom` (`idClassroom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classroon_Equipment_Booking_System`.`Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroon_Equipment_Booking_System`.`Equipment` ;

CREATE TABLE IF NOT EXISTS `Classroon_Equipment_Booking_System`.`Equipment` (
  `id_equipment` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`id_equipment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Classroon_Equipment_Booking_System`.`Borrow_Equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroon_Equipment_Booking_System`.`Borrow_Equipment` ;

CREATE TABLE IF NOT EXISTS `Classroon_Equipment_Booking_System`.`Borrow_Equipment` (
  `idBorrow_Equipment` INT NOT NULL,
  `timestamp` TIMESTAMP(6) NULL,
  `idBorrow` INT NULL,
  `idEquipment` INT NULL,
  `returnTime` DATE NULL,
  `teacher` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `idLendBy` INT NULL,
  `idReturnBy` INT NULL,
  `purpose` VARCHAR(45) NULL,
  `note` VARCHAR(45) NULL,
  PRIMARY KEY (`idBorrow_Equipment`),
  INDEX `idBorrow_idx` (`idBorrow` ASC),
  INDEX `idEquipment_idx` (`idEquipment` ASC),
  INDEX `idLendBy_idx` (`idLendBy` ASC),
  INDEX `idReturnBy_idx` (`idReturnBy` ASC),
  CONSTRAINT `idBorrow`
    FOREIGN KEY (`idBorrow`)
    REFERENCES `Classroon_Equipment_Booking_System`.`Borrow` (`idBorrow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEquipment`
    FOREIGN KEY (`idEquipment`)
    REFERENCES `Classroon_Equipment_Booking_System`.`Equipment` (`id_equipment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idLendBy`
    FOREIGN KEY (`idLendBy`)
    REFERENCES `Classroon_Equipment_Booking_System`.`Member` (`idMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idReturnBy`
    FOREIGN KEY (`idReturnBy`)
    REFERENCES `Classroon_Equipment_Booking_System`.`Member` (`idMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
